package edu.ynu.docmanagesystem.mapper;

import edu.ynu.docmanagesystem.po.Resourcetype;
import edu.ynu.docmanagesystem.po.ResourcetypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourcetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceType
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int countByExample(ResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceType
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int deleteByExample(ResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceType
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int deleteByPrimaryKey(Integer resourcetypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceType
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int insert(Resourcetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceType
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int insertSelective(Resourcetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceType
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    List<Resourcetype> selectByExample(ResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceType
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    Resourcetype selectByPrimaryKey(Integer resourcetypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceType
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") Resourcetype record, @Param("example") ResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceType
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int updateByExample(@Param("record") Resourcetype record, @Param("example") ResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceType
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int updateByPrimaryKeySelective(Resourcetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourceType
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int updateByPrimaryKey(Resourcetype record);
}