package edu.ynu.docmanagesystem.mapper;

import edu.ynu.docmanagesystem.po.Resource;
import edu.ynu.docmanagesystem.po.ResourceExample;
import edu.ynu.docmanagesystem.po.ResourceWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int countByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int deleteByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int deleteByPrimaryKey(Integer resourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int insert(ResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int insertSelective(ResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    List<ResourceWithBLOBs> selectByExampleWithBLOBs(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    List<Resource> selectByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    ResourceWithBLOBs selectByPrimaryKey(Integer resourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") ResourceWithBLOBs record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ResourceWithBLOBs record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int updateByExample(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int updateByPrimaryKeySelective(ResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int updateByPrimaryKey(Resource record);
}