package edu.ynu.docmanagesystem.mapper;

import edu.ynu.docmanagesystem.po.RoleSystemauthorityExample;
import edu.ynu.docmanagesystem.po.RoleSystemauthorityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleSystemauthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int countByExample(RoleSystemauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int deleteByExample(RoleSystemauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int deleteByPrimaryKey(RoleSystemauthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int insert(RoleSystemauthorityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int insertSelective(RoleSystemauthorityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    List<RoleSystemauthorityKey> selectByExample(RoleSystemauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") RoleSystemauthorityKey record, @Param("example") RoleSystemauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    int updateByExample(@Param("record") RoleSystemauthorityKey record, @Param("example") RoleSystemauthorityExample example);
}