package edu.ynu.docmanagesystem.mapper;

import edu.ynu.docmanagesystem.po.Section;
import edu.ynu.docmanagesystem.po.SectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int countByExample(SectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int deleteByExample(SectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int deleteByPrimaryKey(Integer sectionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int insert(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int insertSelective(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    List<Section> selectByExample(SectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    Section selectByPrimaryKey(Integer sectionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") Section record, @Param("example") SectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int updateByExample(@Param("record") Section record, @Param("example") SectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int updateByPrimaryKeySelective(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    int updateByPrimaryKey(Section record);
}