package edu.ynu.docmanagesystem.mapper;

import edu.ynu.docmanagesystem.po.SectionUserauthorityResourcetype;
import edu.ynu.docmanagesystem.po.SectionUserauthorityResourcetypeExample;
import edu.ynu.docmanagesystem.po.SectionUserauthorityResourcetypeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SectionUserauthorityResourcetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_userauthority_ resourcetype
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    int countByExample(SectionUserauthorityResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_userauthority_ resourcetype
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    int deleteByExample(SectionUserauthorityResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_userauthority_ resourcetype
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    int deleteByPrimaryKey(SectionUserauthorityResourcetypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_userauthority_ resourcetype
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    int insert(SectionUserauthorityResourcetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_userauthority_ resourcetype
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    int insertSelective(SectionUserauthorityResourcetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_userauthority_ resourcetype
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    List<SectionUserauthorityResourcetype> selectByExample(SectionUserauthorityResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_userauthority_ resourcetype
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    SectionUserauthorityResourcetype selectByPrimaryKey(SectionUserauthorityResourcetypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_userauthority_ resourcetype
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") SectionUserauthorityResourcetype record, @Param("example") SectionUserauthorityResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_userauthority_ resourcetype
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    int updateByExample(@Param("record") SectionUserauthorityResourcetype record, @Param("example") SectionUserauthorityResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_userauthority_ resourcetype
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    int updateByPrimaryKeySelective(SectionUserauthorityResourcetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_userauthority_ resourcetype
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    int updateByPrimaryKey(SectionUserauthorityResourcetype record);
}