package edu.ynu.docmanagesystem.po;

public class RoleSystemauthorityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_systemAuthority.SystemAuthirityId
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    private Integer systemauthirityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_systemAuthority.roleId
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_systemAuthority.SystemAuthirityId
     *
     * @return the value of role_systemAuthority.SystemAuthirityId
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    public Integer getSystemauthirityid() {
        return systemauthirityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_systemAuthority.SystemAuthirityId
     *
     * @param systemauthirityid the value for role_systemAuthority.SystemAuthirityId
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    public void setSystemauthirityid(Integer systemauthirityid) {
        this.systemauthirityid = systemauthirityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_systemAuthority.roleId
     *
     * @return the value of role_systemAuthority.roleId
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_systemAuthority.roleId
     *
     * @param roleid the value for role_systemAuthority.roleId
     *
     * @mbggenerated Tue Sep 06 14:22:26 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}