package edu.ynu.docmanagesystem.po;

public class SectionUserauthorityResourcetype extends SectionUserauthorityResourcetypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_userauthority_ resourcetype.sectionCascadeId
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    private String sectioncascadeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_userauthority_ resourcetype.sectionCascadeId
     *
     * @return the value of section_userauthority_ resourcetype.sectionCascadeId
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    public String getSectioncascadeid() {
        return sectioncascadeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_userauthority_ resourcetype.sectionCascadeId
     *
     * @param sectioncascadeid the value for section_userauthority_ resourcetype.sectionCascadeId
     *
     * @mbggenerated Mon Sep 05 11:13:59 CST 2016
     */
    public void setSectioncascadeid(String sectioncascadeid) {
        this.sectioncascadeid = sectioncascadeid == null ? null : sectioncascadeid.trim();
    }
}