package edu.ynu.docmanagesystem.po;

public class SectionUserauthorityResourcetypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_userauthority_resourcetype.resourceTypeId
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    private Integer resourcetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_userauthority_resourcetype.sectionId
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    private Integer sectionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_userauthority_resourcetype.userAuthorityId
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    private Integer userauthorityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_userauthority_resourcetype.resourceTypeId
     *
     * @return the value of section_userauthority_resourcetype.resourceTypeId
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public Integer getResourcetypeid() {
        return resourcetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_userauthority_resourcetype.resourceTypeId
     *
     * @param resourcetypeid the value for section_userauthority_resourcetype.resourceTypeId
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public void setResourcetypeid(Integer resourcetypeid) {
        this.resourcetypeid = resourcetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_userauthority_resourcetype.sectionId
     *
     * @return the value of section_userauthority_resourcetype.sectionId
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public Integer getSectionid() {
        return sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_userauthority_resourcetype.sectionId
     *
     * @param sectionid the value for section_userauthority_resourcetype.sectionId
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public void setSectionid(Integer sectionid) {
        this.sectionid = sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_userauthority_resourcetype.userAuthorityId
     *
     * @return the value of section_userauthority_resourcetype.userAuthorityId
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public Integer getUserauthorityid() {
        return userauthorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_userauthority_resourcetype.userAuthorityId
     *
     * @param userauthorityid the value for section_userauthority_resourcetype.userAuthorityId
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public void setUserauthorityid(Integer userauthorityid) {
        this.userauthorityid = userauthorityid;
    }
}