package edu.ynu.docmanagesystem.po;

public class Systemauthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemAuthority.SystemAuthirityId
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    private Integer systemauthirityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemAuthority.systemAuthorityDescribe
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    private String systemauthoritydescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemAuthority.SystemAuthirityId
     *
     * @return the value of systemAuthority.SystemAuthirityId
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public Integer getSystemauthirityid() {
        return systemauthirityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemAuthority.SystemAuthirityId
     *
     * @param systemauthirityid the value for systemAuthority.SystemAuthirityId
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public void setSystemauthirityid(Integer systemauthirityid) {
        this.systemauthirityid = systemauthirityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemAuthority.systemAuthorityDescribe
     *
     * @return the value of systemAuthority.systemAuthorityDescribe
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public String getSystemauthoritydescribe() {
        return systemauthoritydescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemAuthority.systemAuthorityDescribe
     *
     * @param systemauthoritydescribe the value for systemAuthority.systemAuthorityDescribe
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public void setSystemauthoritydescribe(String systemauthoritydescribe) {
        this.systemauthoritydescribe = systemauthoritydescribe == null ? null : systemauthoritydescribe.trim();
    }
}