package edu.ynu.docmanagesystem.po;

import java.util.ArrayList;
import java.util.List;

public class SystemauthorityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public SystemauthorityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSystemauthirityidIsNull() {
            addCriterion("SystemAuthirityId is null");
            return (Criteria) this;
        }

        public Criteria andSystemauthirityidIsNotNull() {
            addCriterion("SystemAuthirityId is not null");
            return (Criteria) this;
        }

        public Criteria andSystemauthirityidEqualTo(Integer value) {
            addCriterion("SystemAuthirityId =", value, "systemauthirityid");
            return (Criteria) this;
        }

        public Criteria andSystemauthirityidNotEqualTo(Integer value) {
            addCriterion("SystemAuthirityId <>", value, "systemauthirityid");
            return (Criteria) this;
        }

        public Criteria andSystemauthirityidGreaterThan(Integer value) {
            addCriterion("SystemAuthirityId >", value, "systemauthirityid");
            return (Criteria) this;
        }

        public Criteria andSystemauthirityidGreaterThanOrEqualTo(Integer value) {
            addCriterion("SystemAuthirityId >=", value, "systemauthirityid");
            return (Criteria) this;
        }

        public Criteria andSystemauthirityidLessThan(Integer value) {
            addCriterion("SystemAuthirityId <", value, "systemauthirityid");
            return (Criteria) this;
        }

        public Criteria andSystemauthirityidLessThanOrEqualTo(Integer value) {
            addCriterion("SystemAuthirityId <=", value, "systemauthirityid");
            return (Criteria) this;
        }

        public Criteria andSystemauthirityidIn(List<Integer> values) {
            addCriterion("SystemAuthirityId in", values, "systemauthirityid");
            return (Criteria) this;
        }

        public Criteria andSystemauthirityidNotIn(List<Integer> values) {
            addCriterion("SystemAuthirityId not in", values, "systemauthirityid");
            return (Criteria) this;
        }

        public Criteria andSystemauthirityidBetween(Integer value1, Integer value2) {
            addCriterion("SystemAuthirityId between", value1, value2, "systemauthirityid");
            return (Criteria) this;
        }

        public Criteria andSystemauthirityidNotBetween(Integer value1, Integer value2) {
            addCriterion("SystemAuthirityId not between", value1, value2, "systemauthirityid");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeIsNull() {
            addCriterion("systemAuthorityDescribe is null");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeIsNotNull() {
            addCriterion("systemAuthorityDescribe is not null");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeEqualTo(String value) {
            addCriterion("systemAuthorityDescribe =", value, "systemauthoritydescribe");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeNotEqualTo(String value) {
            addCriterion("systemAuthorityDescribe <>", value, "systemauthoritydescribe");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeGreaterThan(String value) {
            addCriterion("systemAuthorityDescribe >", value, "systemauthoritydescribe");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeGreaterThanOrEqualTo(String value) {
            addCriterion("systemAuthorityDescribe >=", value, "systemauthoritydescribe");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeLessThan(String value) {
            addCriterion("systemAuthorityDescribe <", value, "systemauthoritydescribe");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeLessThanOrEqualTo(String value) {
            addCriterion("systemAuthorityDescribe <=", value, "systemauthoritydescribe");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeLike(String value) {
            addCriterion("systemAuthorityDescribe like", value, "systemauthoritydescribe");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeNotLike(String value) {
            addCriterion("systemAuthorityDescribe not like", value, "systemauthoritydescribe");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeIn(List<String> values) {
            addCriterion("systemAuthorityDescribe in", values, "systemauthoritydescribe");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeNotIn(List<String> values) {
            addCriterion("systemAuthorityDescribe not in", values, "systemauthoritydescribe");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeBetween(String value1, String value2) {
            addCriterion("systemAuthorityDescribe between", value1, value2, "systemauthoritydescribe");
            return (Criteria) this;
        }

        public Criteria andSystemauthoritydescribeNotBetween(String value1, String value2) {
            addCriterion("systemAuthorityDescribe not between", value1, value2, "systemauthoritydescribe");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table systemAuthority
     *
     * @mbggenerated do_not_delete_during_merge Sat Sep 17 21:42:43 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table systemAuthority
     *
     * @mbggenerated Sat Sep 17 21:42:43 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}